### ISSUE TITLE
"Access Denied" in the brower

### ISSUE THREAD

**Issue by hugjchina** [sagidM/s3-resizer#13] opened 2020-03-01 03:03 UTC
I can test  successful in Lambda , but I test in my chrome brower and the system return "Access Denied". Could help me? Thanks !!
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E6BC853F822F087E</RequestId>
<HostId>
0W84WFaXXRCdQnZa1DWRSzQc0/LRijPbqjqSKf4tejzoXHmwF1nq9c42yWfXJa10i6CWmpBaO88=
</HostId>
</Error>

**Comment by hugjchina** [comment] 2020-03-01 06:10
I resolved the "Access Denied"  , the next problem is 
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>750x750/force.png</Key>
How can I do ?

**Comment by sagidM** [comment] 2020-03-02 11:47
@hugjchina to the best of my understanding, when you do a request to `750x750/force.png`, the image is being processed so that you have a directory named `750x750` with an image `force.png` in your bucket. However, your browser tells you `NoSuckKey`.
And at this point, if you do a request in an incognito mode (CTRL+SHIFT+N in Chrome, CTRL+SHIFT+P in Firefox), you will see the image.

Is everything correct?

**Comment by bynelus** [comment] 2020-06-10 09:30
@hugjchina How did you resolve the Access Denied problem? I'm having the same issue, but can't figure out how to solve it.

**Comment by bynelus** [comment] 2020-06-10 10:24
@sagidM Do you have an idea why I get access denied? I've followed every step, but I think I need to do some policy changes somewhere. This is what I get when testing the Lambda function:
```
{
  "statusCode": 403,
  "body": "Exception: Access Denied",
  "headers": {
    "Content-Type": "text/plain"
  }
}
```

**Comment by sagidM** [comment] 2020-06-28 16:39
@bynelus does `Access Denied` appear on the image put anywhere or just when it is in a nested directory?
Any chance it might be a duplicate of https://github.com/sagidM/s3-resizer/issues/9?

**Closed** 2021-01-30 16:28 UTC
